### ISSUE TITLE
The project "RecordVideo" give a error Visual Studio

### ISSUE THREAD

**Issue by Andrea-Bruno** [xamarin/docs-archive#25]
Under Xamarin for Visual Studio 2015 the project "RecordVideo" cannot work!

```
record.Click += delegate {

                video.StopPlayback ();

                recorder = new MediaRecorder ();
                recorder.SetVideoSource (VideoSource.Camera); 
                recorder.SetAudioSource (AudioSource.Mic);              
                recorder.SetOutputFormat (OutputFormat.Default);
                recorder.SetVideoEncoder (VideoEncoder.Default); 
                recorder.SetAudioEncoder (AudioEncoder.Default);      
                recorder.SetOutputFile (path);       
                recorder.SetPreviewDisplay(video.Holder.Surface);
                recorder.Prepare();
                recorder.Start();
            };
```

The error is: **Java.Lang.RuntimeException: start failed**. at lcode: **recorder.Start();**

I tried in all ways to modify the project, replacing the video object, and delaying the start, so that the surface is created.

The problem is that in my version of Xamarin, the object video fails to create the surface. The surface is not created! Never!

I tried with virtual devices and real, and different versions of the API.

You can adjust the project and make it work with Visual Studio 2015 and the latest version of Xamarin?

**Comment by greg2fs** [comment]
So is there any equivalent sample that work ? I think I have the same problem, it hangs infinitly on recorder.start()...
