### ISSUE TITLE
DisplayPDF Android - Need to hide the top bar and enable pinch zoom

### ISSUE THREAD

**Issue by jamal-deen-EB** [xamarin/docs-archive#30]
In my project I am displaying a `PDF file` from API call. I could able to display the PDF in my `Android` project, however it is showing black color `top bar(title bar)`. I need to disable the `title bar ` as well as I need to enable the `pinch zoom` functionality. is there any possible way to accomplish my changes?.

**Comment by GK1995** [comment]
Hi,

**Comment by GK1995** [comment]
Hi, Have you managed to enable the pinch zoom functionality? If yes, would you mind to share it to me? Thanks

**Comment by jamal-deen-EB** [comment]
No, I haven't implemented yet. I am using `+/-` for zooming.

**Comment by Tonykidv2** [comment]
How are you able get pdf from API call. Did you have to download the file first then display?

`if (e.NewElement != null)
            {
                var customWebView = Element as CustomWebView;
                Control.Settings.AllowUniversalAccessFromFileURLs = true;
                WebClient client = new WebClient();
                string documentsPath = Path.Combine((Android.OS.Environment.GetExternalStoragePublicDirectory(Android.OS.Environment.DirectoryDownloads)).Path, "SampleTag.pdf");
                client.DownloadFile("https://s1.q4cdn.com/806093406/files/doc_downloads/test.pdf", documentsPath);

                Control.LoadUrl(string.Format("file:///android_asset/pdfjs/web/viewer.html?file={0}", string.Format("file://{0}", WebUtility.UrlEncode(documentsPath))));
            }`
